# Use an official lightweight Python image as the base
FROM python:3.9-slim

# Set working directory inside the container
WORKDIR /app

# Copy requirements file from src folder first (for caching)
COPY src/requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the source code and data
COPY src/ .

# Run the training script when the container starts
CMD ["python", "main.py"]
